conky.config = {
    background = true,
    update_interval = 5,
    double_buffer = true,

    own_window = true,
    own_window_type = "override",
    own_window_transparent = true,
    own_window_argb_visual = false,

    alignment = "top_right",
    gap_x = 70,
    gap_y = 70,

    minimum_width = 420,
    maximum_width = 420,
    minimum_height = 370,

    draw_borders = false,
    draw_graph_borders = false,
    draw_outline = false,
    draw_shades = false,

    lua_load = os.getenv("HOME") .. "/.config/conky/calendar.lua",
    lua_draw_hook_pre = "draw_calendar",
};

conky.text = [[
]];
